### ISSUE TITLE
IRR metric do not return 1 for perfect agreement

### ISSUE THREAD

**Issue by UkoZJ** [AndreaCampagner/qualiMLpy#2]
I would like to use the "Weighted Reliability Score" but when I run a test example of full agreement, the score is not equal 1: 

```
from qualiMLpy.metrics.reliability import irr
preds = np.tile(np.random.randint(2, size=1000)[:,None], 2)
print(irr(preds))
# (0.444444444444453, 0.444444444444453)
```

Thank you in advance!

**Comment by AndreaCampagner** [comment]
Hi there, sorry for the issue which is surely caused by the lack of the documentation!
The Weighted Reliability Score is computed as per the method described in:
Cabitza, F., Campagner, A., Albano, D., et al. (2020). The elephant in the machine: Proposing a new metric of data reliability and its application to a medical case to assess classification reliability. Applied Sciences, 10(11), 4014.
Cabitza, F., Campagner, A., Sconfienza, L. M. (2020). As if sand were stone. New concepts and metrics to probe the ground on which to build trustable AI. BMC Medical Informatics and Decision Making, 20(1), 1-21.

In particular, the metric is a chance-discounted reliability metrics in which information about confidence of the decision makers is used to discount the probability that an agreement occurs by chance. These confidence values are given as input through the parameter confs, which as you can see from the code is by default set to np.ones(preds.shape)*0.5. This means that, by default, ratings are associated with a confidence of 0.5, that is it assumes a model of chance in which the rater decided purely at random between the observed rating and a random selection among all ratings.

Thus, the results you obtain are in agreement with the above mentioned model: if you assume that a rater selects "genuinely" the observed label with probability 0.5, then the estimated value of the Weighted Reliability Score would be the value you observe.
If you want to obtain the value 1 for perfect agreement you will have to set the confs parameter to np.ones(preds.shape): note that in this case the Weeighted Reliability coincides with the Po (the simple percentage of agreement) whose use has been discouraged, since it cannot model chance effects!

If you have any questions, please feel free to write me an email!

**Comment by UkoZJ** [comment]
Thanks for the explanation. I close the issue.
